#!/bin/sh

prefix=/c/devkitPro/portlibs/3ds
exec_prefix=${prefix}
exec_prefix_set=no
libdir=${exec_prefix}/lib

#usage="\
#Usage: sdl-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"
usage="\
Usage: sdl-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs] [--static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 1.2.15
      ;;
    --cflags)
      echo -I${prefix}/include/SDL -D_GNU_SOURCE=1 -ffunction-sections -fdata-sections -march=armv6k                      -mtune=mpcore -mfloat-abi=hard -mword-relocations                      -I/c/devkitPro/libctru/include -DARM11 -D_3DS
      ;;
#    --libs)
#      echo -L${exec_prefix}/lib  -specs=3dsx.specs -march=armv6k -mfloat-abi=hard                   -L/c/devkitPro/portlibs/3ds/lib -L/c/devkitPro/portlibs/armv6k/lib -lSDL                    -L/c/devkitPro/libctru/lib -lcitro3d -lctru
#      ;;
#    --static-libs)
    --libs|--static-libs)
      echo -L${exec_prefix}/lib  -specs=3dsx.specs -march=armv6k -mfloat-abi=hard                   -L/c/devkitPro/portlibs/3ds/lib -L/c/devkitPro/portlibs/armv6k/lib -lSDL                    -L/c/devkitPro/libctru/lib -lcitro3d -lctru  -lm
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
